[env]
DESCRIPTORS_BIN = { value = "out/rslib/proto/descriptors.bin", relative = true }
MACOSX_DEPLOYMENT_TARGET = "11"

[term]
color = "always"

[target.'cfg(all(target_env = "msvc", target_os = "windows"))']
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
